apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-run
  name: test-run
spec:
  containers:
  - image: nginx
    name: test-run
    resources: {}
    livenessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
