apiVersion: v1
kind: Pod
metadata:
  labels:
  name: busybox
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /test
        name: test
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 1000"]
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
    - name: test
      emptyDir:
        sizeLimit: 100Mi
