apiVersion: v1
kind: Pod
metadata:
  labels:
  name: mealie
spec:
  containers:
  - image: ghcr.io/mealie-recipes/mealie:latest
    name: mealie
    ports:
      - containerPort: 9000
    volumeMounts:
      - mountPath: /app/data
        name: mealie-data 
  volumes:
    - name: mealie-data
      persistentVolumeClaim:
        claimName: mealie-data
